const fonts = {
  syne: {
    normal: 'Syne-Regular',
    medium: 'Syne-Medium',
    semiBold: 'Syne-SemiBold',
    bold: 'Syne-Bold',
    extraBold: 'Syne-ExtraBold',
    // Jost
    Jostblack: 'Jost-Black',
    JostblackItalic: 'Jost-BlackItalic',
    Jostbold: 'Jost-Bold',
    JostboldItalic: 'Jost-BoldItalic',
    JostextraBold: 'Jost-ExtraBold',
    JostextraBoldItalic: 'Jost-ExtraBoldItalic',
    JostextraLight: 'Jost-ExtraLight',
    JostextraLightItalic: 'Jost-ExtraLightItalic',
    JostItalicVariable: 'Jost-Italic-VariableFont_wght',
    Jostitalic: 'Jost-Italic',
    Jostlight: 'Jost-Light',
    JostlightItalic: 'Jost-LightItalic',
    Jostmedium: 'Jost-Medium',
    JostmediumItalic: 'Jost-MediumItalic',
    Jostregular: 'Jost-Regular',
    JostsemiBold: 'Jost-SemiBold',
    JostsemiBoldItalic: 'Jost-SemiBoldItalic',
    Jostthin: 'Jost-Thin',
    JostthinItalic: 'Jost-ThinItalic',
    JostVariable: 'Jost-VariableFont_wght',
    McJost: 'McLaren-Regular',
  },
  inter: {
    thin: 'Inter_18pt-Thin',
    light: 'Inter_18pt-Light',
    extraLight: 'Inter_18pt-ExtraLight',
    normal: 'Inter_18pt-Regular',
    medium: 'Inter_18pt-Medium',
    semiBold: 'Inter_18pt-SemiBold',
    bold: 'Inter_18pt-Bold',
    extraBold: 'Inter_18pt-ExtraBold',
    black: 'Inter_18pt-Black',
  },
};

export const typography = {
  fonts,
};
